apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gcp-dash
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: gcp-dash
          servicePort: 8080