apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gcp-dash
resources:
  - ../kubernetes
  - ingress.yaml
  - gateway.yaml
  - httproute.yaml

patches:
  - target:
      kind: ServiceAccount
      name: gcp-dash
    patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: gcp-dash
        annotations:
          iam.gke.io/gcp-service-account: gcp-dash@your-project.iam.gserviceaccount.com
          iam.gke.io/return-principal-id-as-email: "true"