apiVersion: v1
kind: Secret
metadata:
  name: gcp-dash-config
stringData:
  # Google Service Account ID
  GSA_ID: gcp-dash@PROJECT_NAME.iam.gserviceaccount.com
  # The numeric ID of your project with the OIDC Endpoint
  PROJECT_NUMBER: "123456789012"
  # Workload Identity Pool Name
  WORKLOAD_IDENTITY_POOL: "ztwim-gcp-dash"
  # Workload Identity Endpoint Trusted Provider Name
  WORKLOAD_PROVIDER_NAME: "ztwim-gcp-dash"
