kind: ConfigMap
apiVersion: v1
metadata:
  name: gcp-spiffe-helper
data:
  entrypoint.sh: |
    #!/bin/bash

    # Set/check needed variables
    DAEMON_MODE="-daemon-mode=false"
    if [ -z "$PROJECT_NUMBER" ]; then echo "PROJECT_NUMBER undefined!"; exit 1; fi
    if [ -z "$WORKLOAD_IDENTITY_POOL" ]; then echo "WORKLOAD_IDENTITY_POOL undefined!"; exit 1; fi
    if [ -z "$WORKLOAD_PROVIDER_NAME" ]; then echo "WORKLOAD_PROVIDER_NAME undefined!"; exit 1; fi

    # Daemon mode runs in the background and keeps the token exchange refreshed, use in the sidecar
    if [ ! -z "$1" ]; then
      DAEMON_MODE="-daemon-mode=true"
    else
      # We only need the Google Service Account ID initially
      if [ -z "$GSA_ID" ]; then echo "GSA_ID undefined!"; exit 1; fi
      
      # This file allows the exchanged token to be used for GCP service access
      cat > /var/run/secrets/gcp/key.json <<EOF
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WORKLOAD_IDENTITY_POOL}/providers/${WORKLOAD_PROVIDER_NAME}",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/gcp/token",
        "format": { "type": "text" }
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${GSA_ID}:generateAccessToken"
    }
    EOF
    fi

    # Create the spiffe-helper configuration dynamically from the environment variables
    cat > /tmp/helper.conf <<EOF
    agent_address = "/run/spire/sockets/spire-agent.sock"
    jwt_svids = [{jwt_audience="https://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WORKLOAD_IDENTITY_POOL}/providers/$WORKLOAD_PROVIDER_NAME", jwt_svid_file_name="/var/run/secrets/gcp/token"}]
    jwt_svid_file_mode = 0644
    EOF
    
    # Execute spiffe-helper
    /spiffe-helper -config /tmp/helper.conf ${DAEMON_MODE}
