apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gcp-dash-ztwim
resources:
  - ../kubernetes
  - route.yaml
  - gcp-spiffe-helper.configmap.yaml
  # - gcp-secret.example.yaml

patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: gcp-dash
  - path: patch-volumemounts.yaml
    target:
      kind: Deployment
      name: gcp-dash
  - path: patch-volumes.yaml
    target:
      kind: Deployment
      name: gcp-dash

  - target:
      kind: Deployment
      name: gcp-dash
    path: patch-initContainers.yaml

  - target:
      kind: Deployment
      name: gcp-dash
    path: patch-refreshSidecar.yaml
