# ConfigMap with spiffe-helper entrypoint and config
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: spiffe-helper
    configMap:
      name: gcp-spiffe-helper
      defaultMode: 493

# SPIRE Socket
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: spiffe-workload-api
    csi:
      driver: csi.spiffe.io
      readOnly: true

# Add a emptyDir volume for sharing between initContainer and main container
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: gcp-ztwim-swap
    emptyDir: {}

# Secrets needed to authenticate to GCP
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: gcp-dash-config
    secret:
      secretName: gcp-dash-config
