- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SPIFFE_ENDPOINT_SOCKET
    value: unix:///run/spire/sockets/spire-agent.sock
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOOGLE_APPLICATION_CREDENTIALS
    value: /var/run/secrets/gcp/key.json