---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gcp-dash
spec:
  to:
    kind: Service
    name: gcp-dash
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
