apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gcp-dash
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: gcp-dash
    newName: ghcr.io/kenmoini/gcp-dash   # change to your registry
    newTag: 9ec424a0dacef7d16a2615c69e2fe0d841879aaa
